import type { SlashCommand } from "@earendil-works/pi-tui";

/** Discoverability only: command dispatch and authorization remain in CasperApp. */
export const COMMANDS: SlashCommand[] = [
  { name: "model", description: "Change model (remembered globally; --session for temporary)" },
  { name: "effort", description: "Reasoning effort, including auto; Shift+Tab cycles and remembers it" },
  { name: "status", description: "Inspect project, model, auth and integrations" },
  { name: "help", description: "Find a command; /help all shows the full reference" },
  { name: "context", description: "Inspect context estimates and capability counts" },
  { name: "usage", description: "Inspect session tokens and available cost estimates" },
  { name: "compact", description: "Summarize context (sends a model request)" },
  { name: "clear", description: "Start a fresh conversation; keep files and saved conversations" },
  { name: "resume", description: "List or resume saved conversations in this workspace" },
  { name: "diff", description: "Inspect current workspace changes" },
  { name: "output", description: "Full retained output of a recent tool call (/output [n])" },
  { name: "verify", description: "Run repository verification checks" },
  { name: "receipt", description: "Evidence behind the last task's receipt" },
  { name: "project", description: "Inspect project stack, configuration and checks" },
  { name: "skills", description: "Inspect skill metadata, trust and warnings" },
  { name: "mcp", description: "MCP status; connect, disconnect, writes on/off, forget, docs servers" },
  { name: "lsp", description: "Inspect language-server status; connect or disconnect" },
  { name: "browser", description: "Inspect a disposable browser; capture a screenshot" },
  { name: "services", description: "Declared services: status, logs, start, restart, stop" },
  { name: "debug", description: "Inspect local targets; approve launch and debug code" },
  { name: "permissions", description: "Understand native-tool risks and exact approval boundaries" },
  { name: "tree", description: "Inspect named conversations and workspaces" },
  { name: "branch", description: "Create a named workspace conversation (requires approval)" },
  { name: "switch", description: "Switch named workspace conversation (requires approval)" },
  { name: "memory", description: "Manage explicit project facts and inspect task outcomes" },
  { name: "references", description: "Search local reference projects; add a vendor spec repo" },
  { name: "secrets", description: "Show what Casper hides from the AI" },
  { name: "visualize", description: "Inspect providers or render repository dependencies" },
  { name: "delegate", description: "Ask a bounded read-only subagent (uses a model)" },
  { name: "login", description: "Set up provider credentials in a private login flow" },
  { name: "exit", description: "Leave Casper" },
];
